USE DataView;

-- Add scoring columns to GLOBAL_FILE_CATALOG
ALTER TABLE file_catalog.GLOBAL_FILE_CATALOG ADD
    CATALOG_SCORE       INT            NULL,
    CATALOG_READINESS   NVARCHAR(20)   NULL,
    MATCHED_UWI         NVARCHAR(40)   NULL,
    MATCH_METHOD        NVARCHAR(40)   NULL,
    CATALOG_ISSUES      NVARCHAR(2000) NULL,
    HEADER_EXTRACTED    NVARCHAR(1)    NULL DEFAULT 'N';

-- Index for readiness filtering
CREATE INDEX IX_GFC_READINESS
ON file_catalog.GLOBAL_FILE_CATALOG (CATALOG_READINESS, CATALOG_STATUS);

CREATE INDEX IX_GFC_MATCHED_UWI
ON file_catalog.GLOBAL_FILE_CATALOG (MATCHED_UWI)
WHERE MATCHED_UWI IS NOT NULL;
